package com.example;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan(basePackages = {"com.example.dao", "com.example.mapper"})
public class Springboot017MapperApplication {

    public static void main(String[] args) {
        SpringApplication.run(Springboot017MapperApplication.class, args);
    }

}
