package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class Springboot090JspApplication {

	public static void main(String[] args) {
		SpringApplication.run(Springboot090JspApplication.class, args);
	}

}
